version: '3.9'
services:
    db:
        container_name: mysql
        image: 'mysql:latest'
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        tty: true
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '3306:3306'
        networks:
            - local-net

    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE}
        volumes:
            - ./:/code
        ports:
            - '80:80'
        networks:
            - local-net

networks:
    local-net:
        driver: bridge